on:
  release:
    types:
      - created

name: release
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - id: release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Install nfpm
        run: |
          wget https://github.com/goreleaser/nfpm/releases/download/v2.2.3/nfpm_2.2.3_Linux_x86_64.tar.gz
          tar zxvf nfpm_2.2.3_Linux_x86_64.tar.gz

      - name: Build Browser
        run: |
          mkdir -p dist
          cp release/browser.service dist
          cat release/nfpm.yml | BROWSER_VERSION=${{ steps.release.outputs.tag_name }} envsubst > dist/nfpm.yml
          go build -o dist/browser ./cmd/browser/main.go

          cd dist
          tar -czvf browser-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz browser
          ../nfpm pkg --config nfpm.yml --packager deb --target browser-${{ steps.release.outputs.tag_name }}-linux-amd64.deb

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./dist/browser-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz
          asset_name: browser-${{ steps.release.outputs.tag_name }}-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload debian package
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./dist/browser-${{ steps.release.outputs.tag_name }}-linux-amd64.deb
          asset_name: browser-${{ steps.release.outputs.tag_name }}-linux-amd64.deb
          asset_content_type: application/octet-stream